<div class="right-content">
    <div class="box green">
        <a href="/issues/new" class="button green">New Issue</a>
    </div>
    
    <div class="box white issues-in-progress-box" style="display: none;">
        <h1>In Progress</h1>
        <div class="issues-in-progress"></div>
    </div>
</div>

<div class="left-column content shadow">
    <h1>Assigned To Me<span class="issue-quantity right"><a title="<?php echo $this->total; ?> Issues" rel="tipsyleft"><?php echo $this->total; ?></a></span></h1>
    
    <?php echo $this->ListIssues($this->issues); ?>
    
    <?php echo $pagination = $this->Pagination('/issues/mine/?page=%s', $this->page, $this->limit, $this->total); ?>
</div>
