<form action="" method="post" autocomplete="off">

<div class="right-content">
    <div class="box blue">
        
        <div class="category-throbber right" style="display: none;">
            <div class="throbber"></div>
        </div>
        
        <h1>Issue Details</h1>
        
        <table>
            <tr>
                <td class="issue-overview-title">Project</td>
                <td class="issue-overview-data">
                    <select name="issue[project]" id="project" onchange="updateCategoriesFromNew();">
                        <option value="">None</option>
                        <?php foreach ($this->projects as $key => $val): ?>
                        <option value="<?php echo $val['id']; ?>" <?php echo ($this->issue['project'] == $val['id']) ? 'selected="selected"' : ''; ?>><?php echo $val['name']; ?></option>
                        <?php endforeach;  ?>
                    </select>
                </td>
            </tr>
            <tr class="categories-holder" <?php echo (count($this->categories) == 0) ? 'style="display: none;"' : ''; ?>>
                <td class="issue-overview-title">Category</td>
                <td class="issue-overview-data">
                    <select name="issue[category]" class="categories">
                        <option value="">None</option>
                        <?php if (count($this->categories) > 0): ?>
                        <?php foreach ($this->categories as $key => $val): ?>
                        <option value="<?php echo $val['id']; ?>" <?php echo ($this->issue['category'] == $val['id']) ? 'selected="selected"' : ''; ?>><?php echo $val['name']; ?></option>
                        <?php endforeach;  ?>
                        <?php endif; ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="issue-overview-title">Priority</td>
                <td class="issue-overview-data">
                    <select name="issue[priority]">
                        <?php foreach ($this->priorities as $key => $val): ?>
                        <option value="<?php echo $key; ?>" <?php echo ($this->issue['priority'] == $key) ? 'selected="selected"' : '' ?>><?php echo $val; ?></option>
                        <?php endforeach;  ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="issue-overview-title">Assign to</td>
                <td class="issue-overview-data">
                    <select name="issue[assignee]">
                        <option value="">Nobody</option>
                        <?php foreach ($this->users as $key => $val): ?>
                        <option value="<?php echo $val['id']; ?>" <?php echo (isset($this->issue['assignee']) && $this->issue['assignee'] == $val['username'] || $this->issue['assignee'] == $val['id']) ? 'selected="selected"' : ''; ?>><?php echo $val['name']; ?></option>
                        <?php endforeach;  ?>
                    </select>
                </td>
            </tr>
            <tr>
                <td class="issue-overview-title">Milestone</td>
                <td class="issue-overview-data">
                    <select name="issue[milestone]">
                        <option value="">None</option>
                        <?php foreach ($this->milestones as $key => $val): ?>
                        <option value="<?php echo $val['id']; ?>" <?php echo ($this->issue['milestone'] == $val['id']) ? 'selected="selected"' : ''; ?>><?php echo $val['name']; ?></option>
                        <?php endforeach;  ?>
                    </select>
                </td>
            </tr>
        </table>
    </div>
</div>

<div class="left-column content shadow">
    <h1>New Issue</h1>
    
    <div>
        <div class="form-row">
            <div class="form-label">Subject</div>
            <div class="form-field"><input type="text" name="issue[subject]" value="<?php echo $this->issue['subject']; ?>" autofocus="autofocus" placeholder="Quick summary of the issue" /></div>
        </div>
        <div class="form-row">
            <div class="form-label">Description</div>
            <div class="form-field"><textarea name="issue[description]" placeholder="Describe the issue here" class="tall"><?php echo $this->issue['description']; ?></textarea></div>
            <div class="form-field hint">You can use <a href="http://daringfireball.net/projects/markdown/" target="_blank">Markdown</a> formatting.</div>
        </div>
    </div>
    
    <div class="form-buttons">
        <input type="submit" value="Save Issue" class="button green" /> <a href="/issues/mine">cancel and go back</a>
    </div>
</div>

</form>
