<div class="right-content">
    <div class="box white">
        <h1>Limitations</h1>
        
        <table>
            <tr>
                <td class="issue-overview-title">Max Projects</td>
                <td class="issue-overview-data"><?php echo $this->limitations['projects'] ?></td>
            </tr>
            <tr>
                <td class="issue-overview-title">Max Users</td>
                <td class="issue-overview-data"><?php echo $this->limitations['users'] ?></td>
            </tr>
            <tr>
                <td class="issue-overview-title">Max Disk Size</td>
                <td class="issue-overview-data"><?php echo $this->limitations['size'] ?>MB</td>
            </tr>
        </table>
    </div>
</div>

<div class="left-column content shadow">
    <h1>Account Management</h1>
    
    <div class="info-box">
        <h1>What's missing here?</h1>
        <p>We wanted to get the hosted version of Bugify up and running ASAP, so we skipped a couple of corners - this page being one of them.  Normally this page would let you manage your account (i.e., change plans etc).  If you would like to upgrade your account, please send an email to <a href="mailto:support@bugify.com">support@bugify.com</a> with your domain, and which plan you would like to upgrade to - we will get it sorted ASAP.</p>
    </div>
</div>
