<div class="right-content">
    <div class="box green">
        <a class="button green" href="/issues/new">New Issue</a>
    </div>
    
    <div class="box white">
        <h1>History Period</h1>
        
        <form action="" method="get">
        <table>
            <tr>
                <td class="issue-overview-title">Period</td>
                <td class="issue-overview-data">
                    <select name="period">
                        <?php foreach ($this->periods as $key => $val): ?>
                            <option value="<?php echo $key; ?>" <?php echo ($this->period == $key) ? 'selected="selected"' : ''; ?>><?php echo $val['name']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
        </table>
        
        <input type="submit" class="button gray" value="Show History" />
        
        </form>
    </div>
</div>

<div class="left-column content shadow">
    <h1>History</h1>
    
    <?php echo $this->ListHistory($this->history, true); ?>
    <?php echo $pagination = $this->Pagination('/history/?page=%s&period='.$this->period, $this->page, $this->limit, $this->total); ?>
</div>
