<div class="right-content">
    <div class="box green">
        <a class="button green" href="/issues/new/?user=<?php echo $this->user['username']; ?>">New Issue</a>
    </div>
</div>

<div class="left-column content shadow">
    <h1>Assigned To <?php echo $this->user['name'] ?><span class="issue-quantity right"><a title="<?php echo $this->total; ?> Issues" rel="tipsyleft"><?php echo $this->total; ?></a></span></h1>
    
    <?php echo $this->ListIssues($this->issues); ?>
    
    <?php echo $pagination = $this->Pagination('/users/'.$this->user['username'].'/issues/?page=%s', $this->page, $this->limit, $this->total); ?>
</div>
