
<div class="left-column content shadow">
    <h1>New User</h1>
    <form action="" method="post" autocomplete="off">
        <div>
            <div class="form-row">
                <div class="form-label">First name</div>
                <div class="form-field"><input type="text" name="user[firstname]" value="<?php echo $this->add_user['firstname']; ?>" autofocus="autofocus" /></div>
            </div>
            <div class="form-row">
                <div class="form-label">Last name</div>
                <div class="form-field"><input type="text" name="user[lastname]" value="<?php echo $this->add_user['lastname']; ?>" /></div>
            </div>
            <div class="form-row">
                <div class="form-label">Email</div>
                <div class="form-field"><input type="email" name="user[email]" value="<?php echo $this->add_user['email']; ?>" /></div>
            </div>
            <div class="form-row">
                <div class="form-label">Username</div>
                <div class="form-field"><input type="text" name="user[username]" value="<?php echo $this->add_user['username']; ?>" autocapitalize="off" autocorrect="off" /></div>
            </div>
            <div class="form-row">
                <div class="form-label">Password</div>
                <div class="form-field"><input type="password" name="user[password]" value="" /></div>
            </div>
            
        </div>
        
        <div class="form-buttons">
            <input type="submit" value="Save User" class="button green" /> <a href="/users">cancel and go back</a>
        </div>
    </form>
</div>
