<div class="right-content">
    <div class="box green">
        <a class="button green" href="/mailboxes/new">Add Mailbox</a>
    </div>
</div>

<div class="left-column content shadow">
    <h1>Mailboxes</h1>
    
    <div class="info-box">
        <h1>Why mailboxes?</h1>
        <p>Setup mailboxes to automatically check for new messages.  Any new emails (from known users) will be added as issues - making it easier for you to get your ideas recorded.</p>
    </div>
    
    <?php if (count($this->mailboxes) > 0): ?>
    <table class="mailbox-list">
        <?php foreach($this->mailboxes as $key => $val): ?>
        <tr>
            <td>
                <?php echo sprintf('<a href="/mailboxes/%s">%s</a>', $val['id'], $val['name']); ?>
                <div class="meta"><?php echo sprintf('Last checked <a title="%s" rel="tipsydown">%s</a>', $val['last_checked'], $this->RelativeDate($val['last_checked'])); ?>.</div>
            </td>
            <td><?php echo $val['username']; ?></td>
            <td><?php echo $val['host']; ?></td>
            <td><a href="#check-now" onclick="checkForMessages('<?php echo $val['id']; ?>'); return false;">Check now</a></td>
        </tr>
        <?php endforeach; ?>
    </table>
    <?php endif; ?>
</div>
